### PR TITLE
update java-spdx to 1.1.8

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

- update license data to v3.24.0
/assign @puerco @saschagrunert @xmudrii 
cc @kubernetes-sigs/release-engineering 

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
update license data to v3.24.0
```

### CODE REVIEW

**Comment by cpanato** [comment]
looks like the new licenses broke the validation

```
This SPDX Document is not valid due to:
        License list version does not match the pattern M.N
```

cc @puerco

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by xmudrii** [comment]
Ah, didn't see the comment
/lgtm cancel

**Comment by puerco** [comment]
I brought this issue to SPDX. [The license list version format is baked into the SPDX spec](https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#67-license-list-version-field), I think we will need to double tag the license list release for any automation to work with SPDX 2.x documents. I will raise it in the community meeting.

**Comment by puerco** [comment]
The license list was updated in https://github.com/kubernetes-sigs/release-utils/commit/9c4908275a6d6121ca95140b91e12ad5c2955d39 as part of the fix in #462, I think we can keep the spdx tools bump in this PR.

**Comment by cpanato** [comment]
PTAL @puerco

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
