### PR TITLE
update docs with new install instruction

### PR DESCRIPTION
**Pull request by spiffcs**
Signed-off-by: Christopher Angelo Phillips <christopher.phillips@anchore.com>

#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Add docs clarity for installation.

#### Special notes for your reviewer:
See Screenshot for updated install command that works

#### Does this PR introduce a user-facing change?
NONE

Screen Shot 2021-12-01 at 3 58 45 PM

### CODE REVIEW

**Comment by puerco** [comment]
Thanks for the update @spiffcs ! Just sign the CLA so that the bot lets us merge the PR!

**Comment by spiffcs** [comment]
@puerco Yep! Signing and going through the process now. Just signed it on docusign and working to make sure it's all verified.

**Comment by spiffcs** [comment]
Just waiting for the EasyCLA check to update. Just signed it.

**Comment by puerco** [comment]
Let's try this:
/check-cla

**Comment by spiffcs** [comment]
Mmm - I'll check my Linux Foundation account and see what the disconnect is from what I signed for the CLA. Thanks for the quick follow up!

**Comment by spiffcs** [comment]
Mmm - I'll check my Linux Foundation account and see what the disconnect is from what I signed for the CLA. Thanks for the quick follow up!

**Comment by puerco** [comment]
Ready!
/lgtm
/approve

**Pull request merged**
