### PR TITLE
Add canary image promotion jobs

### PR DESCRIPTION
**Pull request by puerco**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:

We now promote canary images for bom prereleases

Signed-off-by: Adolfo García Veytia (Puerco) <adolfo.garcia@uservers.net>

#### Special notes for your reviewer:

/assign @cpanato 

#### Does this PR introduce a user-facing change?

```release-note
We now have image promotion manifests for canary jobs
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
lets try out

**Comment by puerco** [comment]
Job is merged: https://github.com/kubernetes/test-infra/pull/25850

/hold cancel

**Pull request merged**
