### PR TITLE
Migrate in `k8s.io/release/cmd/bom` and associated packages

### PR DESCRIPTION
**Pull request by justaugustus**
/hold for module fixups
ref: https://github.com/kubernetes/org/issues/3106

FYI to previous contributors of this code: @puerco @hasheddan @saschagrunert @mattmoor @cpanato @hectorj2f @jayonlau

---

(Also, woooo, I found yet another way to migrate content!)

Figure out what to migrate:

```console
❯ go list -deps ./cmd/bom/... | grep k8s.io/release/
k8s.io/release/pkg/license
k8s.io/release/pkg/provenance
k8s.io/release/pkg/spdx
k8s.io/release/cmd/bom/cmd
k8s.io/release/cmd/bom
```

Package up the commit history as packages:

```console
❯ git format-patch -o /tmp/mergepatchs \
$(git log cmd/bom/ docs/bom/ pkg/license/ pkg/provenance/ pkg/spdx/|grep ^commit|tail -1|awk '{print $2}')^..HEAD \
cmd/bom/ docs/bom/ pkg/license/ pkg/provenance/ pkg/spdx/
```

<details>

```console
/tmp/mergepatchs/0001-k8s.io-release-pkg-license-package.patch
/tmp/mergepatchs/0002-License-package-implementation-fakes.patch
/tmp/mergepatchs/0003-License-package-tests.patch
/tmp/mergepatchs/0004-Use-dateless-license-boilerplate-in-all-generated-go.patch
/tmp/mergepatchs/0005-Update-import-references-to-sigs.k8s.io-release-util.patch
/tmp/mergepatchs/0006-Move-from-ioutil-to-os-io-packages.patch
/tmp/mergepatchs/0007-Spin-SPDX-into-own-package.patch
/tmp/mergepatchs/0008-Refactor-SPDX-pkg-to-implementation.patch
/tmp/mergepatchs/0009-SPDX-Document-builder.patch
/tmp/mergepatchs/0010-Image-analyzer-packages.patch
/tmp/mergepatchs/0011-Split-license-interface-to-catalog-obj.patch
/tmp/mergepatchs/0012-Split-license-logic-to-implementation.patch
/tmp/mergepatchs/0013-Update-license-and-download-code-to-new-interfaces.patch
/tmp/mergepatchs/0014-Write-license-files-in-prallel-and-unexport-catalog-.patch
/tmp/mergepatchs/0015-Update-license-tests-and-fakes.patch
/tmp/mergepatchs/0016-SPDX-pkg-unit-and-integration-tests.patch
/tmp/mergepatchs/0017-Regenerate-SPDX-package-fakes.patch
/tmp/mergepatchs/0018-BOM-utility-Generate-SPDX-docs.patch
/tmp/mergepatchs/0019-Consolidate-license-directories-and-naming.patch
/tmp/mergepatchs/0020-Fix-bug-where-lic-dnld-errors-where-lost.patch
/tmp/mergepatchs/0021-Go-module-supprt.patch
/tmp/mergepatchs/0022-Directory-scanning-support.patch
/tmp/mergepatchs/0023-Full-support-for-.gitignore-files-and-patterns.patch
/tmp/mergepatchs/0024-Add-package-dependency-capabilities.patch
/tmp/mergepatchs/0025-Import-add-go-packages-as-pkg-deps.patch
/tmp/mergepatchs/0026-Ensure-package-files-are-checksummed-at-the-right-ti.patch
/tmp/mergepatchs/0027-Scan-go.mod-when-checking-directories.patch
/tmp/mergepatchs/0028-Correctly-implement-LicenseInfoFromFiles-in-spdx-pac.patch
/tmp/mergepatchs/0029-Handle-go-module-downloads-by-commit-sha.patch
/tmp/mergepatchs/0030-Allow-bom-generate-command-to-read-directories-from-.patch
/tmp/mergepatchs/0031-Parallelize-go-module-downloads.patch
/tmp/mergepatchs/0032-Shift-license-output-to-debug-and-fix-div-0-bug.patch
/tmp/mergepatchs/0033-Include-full-list-of-transient-dependencies-in-SBOM.patch
/tmp/mergepatchs/0034-Regenerate-SPDX-fakes.patch
/tmp/mergepatchs/0035-Move-spdx-keywords-NONE-and-NOASSERTION-to-constants.patch
/tmp/mergepatchs/0036-Prewarm-license-cache-during-release.PrepareWorkspac.patch
/tmp/mergepatchs/0037-Reduce-SPDX-file-verbosity.patch
/tmp/mergepatchs/0038-HOWTO-Guide-about-creating-a-BOM.patch
/tmp/mergepatchs/0039-bom-utility-README-file.patch
/tmp/mergepatchs/0040-bom-command-documentation.patch
/tmp/mergepatchs/0041-Add-support-for-configuring-BOM-in-a-YAML-file.patch
/tmp/mergepatchs/0042-Add-more-fields-to-document-build-options.patch
/tmp/mergepatchs/0043-Unit-test-file-for-doc-builder.patch
/tmp/mergepatchs/0044-Parallelize-file-processing.patch
/tmp/mergepatchs/0045-Fix-error-in-go-modules-flag.patch
/tmp/mergepatchs/0046-Make-directory-paths-relative.patch
/tmp/mergepatchs/0047-Use-cached-package-replacements.patch
/tmp/mergepatchs/0048-Avoid-erasing-modules-from-GOPATH.patch
/tmp/mergepatchs/0049-Correct-cache-data-directories-handling.patch
/tmp/mergepatchs/0050-Return-full-license-text-after-scanning.patch
/tmp/mergepatchs/0051-Switch-to-license.ReadTopLicense.patch
/tmp/mergepatchs/0052-Regenerate-license-fakes.patch
/tmp/mergepatchs/0053-Use-native-errors-methods-instead-of-fmt.Sprintf.patch
/tmp/mergepatchs/0054-spdx.buildIDString-function.patch
/tmp/mergepatchs/0055-Fix-spdx-date-bug.patch
/tmp/mergepatchs/0056-Download-all-platforms-when-generating-spdx-packages.patch
/tmp/mergepatchs/0057-Object-interface.patch
/tmp/mergepatchs/0058-SPDX-Relationships.patch
/tmp/mergepatchs/0059-Fix-template-bug.patch
/tmp/mergepatchs/0060-Fix-bug-downloading-packages.patch
/tmp/mergepatchs/0061-Add-ExternalDocRef-to-SPDX-package.patch
/tmp/mergepatchs/0062-Regenrate-layer-SPDX-ID-to-add-imageref.patch
/tmp/mergepatchs/0063-SBOM-Link-source-SBOM-to-artifacts-SBOM.patch
/tmp/mergepatchs/0064-Ensure-SPDX-relationship-rednering.patch
/tmp/mergepatchs/0065-SPDX-Support-relationships-with-remote-entities.patch
/tmp/mergepatchs/0066-License-Catalog-Ignore-deprecated-license-IDs.patch
/tmp/mergepatchs/0067-SPDX-Correctly-form-layer-ref-for-single-img-ref.patch
/tmp/mergepatchs/0068-fix-panic-when-LICENSE-file-is-not-found.patch
/tmp/mergepatchs/0069-Clean-up-extra-spaces.patch
/tmp/mergepatchs/0070-lint-revive-Fixup-variable-declaration-warnings.patch
/tmp/mergepatchs/0071-lint-nolintlint-Enforce-stricter-settings.patch
/tmp/mergepatchs/0072-Fix-SPDX-relationship-order-btw-images-and-ref.patch
/tmp/mergepatchs/0073-Support-license-definition-from-command-flag.patch
/tmp/mergepatchs/0074-go-pkg-provenance.patch
/tmp/mergepatchs/0075-generate-provenance-fakes.patch
/tmp/mergepatchs/0076-pkg-provenance-tests.patch
/tmp/mergepatchs/0077-Add-possibility-to-build-custom-Kubernetes-forks.patch
/tmp/mergepatchs/0078-provenance-Add-LoadStatement-func.patch
/tmp/mergepatchs/0079-provenance-Add-Test-data.patch
/tmp/mergepatchs/0080-provenance-Add-ClonePredicate-function.patch
/tmp/mergepatchs/0081-provenance-statment.VerifySubjects.patch
/tmp/mergepatchs/0082-VerifySubjects-unit-test.patch
/tmp/mergepatchs/0083-lint-gosec-Add-nolint-s-for-SHA1-file-integrity-usag.patch
/tmp/mergepatchs/0084-lint-gosec-Guard-against-decompression-bombs-when-us.patch
/tmp/mergepatchs/0085-lint-gosec-Guard-against-decompression-bombs-when-us.patch
/tmp/mergepatchs/0086-spdx-Fix-panic-when-unable-to-dnload-err.patch
/tmp/mergepatchs/0087-SPDX-Parser.patch
/tmp/mergepatchs/0088-SPDX-Banner.patch
/tmp/mergepatchs/0089-lint-Fix-typo.patch
/tmp/mergepatchs/0090-spdx-Document-outliner.patch
/tmp/mergepatchs/0091-bom-document-outline-subcommand.patch
/tmp/mergepatchs/0092-Switch-to-buffered-output-of-the-outline.patch
/tmp/mergepatchs/0093-spdx-Use-1-to-represent-unlimited-recursion-in-outli.patch
/tmp/mergepatchs/0094-spdx-Make-regular-expressions-global-to-avoid-recomp.patch
/tmp/mergepatchs/0095-spdx-parser-Fix-bug-in-File.Name-and-NONE-Dnld.patch
/tmp/mergepatchs/0096-spdx-SLSA-Provenance-export.patch
/tmp/mergepatchs/0097-Regenerate-provenance-fakeks.patch
/tmp/mergepatchs/0098-provenance-Rewrite-links-to-artifact-locations-in-th.patch
/tmp/mergepatchs/0099-Fix-several-typos-nits-in-comments.patch
```

</details>

Apply the patches to the new repo:

```console
❯ git am /tmp/mergepatchs/*.patch
```

<details>

```console
Applying: k8s.io/release/pkg/license package
Applying: License package implementation fakes
Applying: License package tests
Applying: Use dateless license boilerplate in all generated go files
Applying: Update import references to sigs.k8s.io/release-utils
Applying: Move from ioutil to os/io packages
Applying: Spin SPDX into own package
Applying: Refactor SPDX pkg to implementation
Applying: SPDX Document builder
Applying: Image analyzer packages
Applying: Split license interface to catalog obj
Applying: Split license logic to implementation
Applying: Update license and download code to new interfaces
Applying: Write license files in prallel and unexport catalog options
Applying: Update license tests and fakes
Applying: SPDX pkg unit and integration tests
Applying: Regenerate SPDX package fakes
Applying: BOM utility: Generate SPDX docs
.git/rebase-apply/patch:217: trailing whitespace.
the libraries developed for the Kubernetes SBOM for other
warning: 1 line adds whitespace errors.
Applying: Consolidate license directories and naming
Applying: Fix bug where lic dnld errors where lost
Applying: Go module supprt
Applying: Directory scanning support
Applying: Full support for .gitignore files and patterns
Applying: Add package dependency capabilities
Applying: Import add go packages as pkg deps
Applying: Ensure package files are checksummed at the right times
Applying: Scan go.mod when checking directories
Applying: Correctly implement LicenseInfoFromFiles in spdx packages
Applying: Handle go module downloads by commit sha
Applying: Allow bom generate command to read directories from arguments
Applying: Parallelize go module downloads
Applying: Shift license output to debug and fix div/0 bug
Applying: Include full list of transient dependencies in SBOM
Applying: Regenerate SPDX fakes
Applying: Move spdx keywords NONE and NOASSERTION to constants
Applying: Prewarm license cache during release.PrepareWorkspaceStage()
Applying: Reduce SPDX file verbosity
Applying: HOWTO Guide about creating a BOM
.git/rebase-apply/patch:35: trailing whitespace.
To generate a Bill of Materials for your project, download `bom`, our utility
.git/rebase-apply/patch:40: trailing whitespace.
bom -n 'http://mybom.com/' .
.git/rebase-apply/patch:44: trailing whitespace.
for more information about our tools, SBOMs, and the SPDX standard.
.git/rebase-apply/patch:64: trailing whitespace.
SBOM can express all of them in the same document.
.git/rebase-apply/patch:90: trailing whitespace.
by the SPDX Workgroup, a project of the Linux Foundation.
warning: squelched 6 whitespace errors
warning: 11 lines add whitespace errors.
Applying: bom utility README file
.git/rebase-apply/patch:16: trailing whitespace.
Bill of Materials project. It enables software authors to generate an
.git/rebase-apply/patch:23: trailing whitespace.
has a built-in license classifier that recognizes the 400+ licenses in
.git/rebase-apply/patch:32: trailing whitespace.
have created a
.git/rebase-apply/patch:74: trailing whitespace.
bom generate -n http://example.com/ --image k8s.gcr.io/kube-apiserver:v1.21.0
.git/rebase-apply/patch:86: trailing whitespace.
    -f other/file.txt
warning: 5 lines add whitespace errors.
Applying: bom command documentation
.git/rebase-apply/patch:459: trailing whitespace.
Create SPDX compliant Bill of Materials
.git/rebase-apply/patch:465: trailing whitespace.
## Summary
.git/rebase-apply/patch:474: trailing whitespace.
the libraries developed for the Kubernetes SBOM for other
.git/rebase-apply/patch:523: trailing whitespace.
Create SPDX compliant Bill of Materials
.git/rebase-apply/patch:529: trailing whitespace.
## Summary
warning: 5 lines add whitespace errors.
Applying: Add support for configuring BOM in a YAML file
Applying: Add more fields to document build options
Applying: Unit test file for doc builder
Applying: Parallelize file processing
Applying: Fix error in go modules flag
Applying: Make directory paths relative
Applying: Use cached package replacements
Applying: Avoid erasing modules from GOPATH
Applying: Correct cache/data directories handling
Applying: Return full license text after scanning
Applying: Switch to license.ReadTopLicense()
Applying: Regenerate license fakes
Applying: Use native `errors` methods instead of `fmt.Sprintf`
Applying: spdx.buildIDString function
Applying: Fix spdx date bug
Applying: Download all platforms when generating spdx packages from images
Applying: Object interface
Applying: SPDX Relationships
Applying: Fix template bug
Applying: Fix bug downloading packages
Applying: Add ExternalDocRef to SPDX package
Applying: Regenrate layer SPDX ID to add imageref
Applying: SBOM: Link source SBOM to artifacts SBOM
Applying: Ensure SPDX relationship rednering
Applying: SPDX: Support relationships with remote entities
Applying: License Catalog: Ignore deprecated license IDs
Applying: SPDX: Correctly form layer ref for single img ref
Applying: fix: panic when LICENSE file is not found
Applying: Clean up extra spaces
Applying: lint(revive): Fixup variable declaration warnings
Applying: lint(nolintlint): Enforce stricter settings
Applying: Fix SPDX relationship order btw images and ref
Applying: Support license definition from command flag
Applying: Add possibility to build custom Kubernetes forks
Applying: lint(gosec): Add `nolint`s for SHA1 file integrity usage
Applying: lint(gosec): Guard against decompression bombs when using `io.Copy`
Applying: lint(gosec): Guard against decompression bombs when using filepath.Join
Applying: spdx: Fix panic when unable to dnload err
Applying: SPDX Parser
Applying: SPDX Banner
Applying: lint: Fix typo
Applying: spdx: Document outliner
Applying: bom: document outline subcommand
Applying: Switch to buffered output of the outline
.git/rebase-apply/patch:41: trailing whitespace.
This subcommand draws a tree-like outline to help the user visualize
.git/rebase-apply/patch:42: trailing whitespace.
the structure of the bom. Even when an SBOM represents a graph structure,
.git/rebase-apply/patch:47: trailing whitespace.
attached directly to the root of the document.
warning: 3 lines add whitespace errors.
Applying: spdx: Use -1 to represent unlimited recursion in outline
Applying: spdx: Make regular expressions global to avoid recompiling
Applying: spdx parser: Fix bug in File.Name and NONE Dnld
Applying: spdx: SLSA Provenance export
Applying: Fix several typos/nits in comments
```

</details>

ref: https://dxarts.washington.edu/wiki/git-tricks#copy

### CODE REVIEW

**Comment by imjasonh** [comment]
FYI I'm looking forward to using this in https://github.com/google/ko/pull/507 -- and contributing any changes I can to make it easier to translate the output of `go version -m` into SPDX (and someday CycloneDX, and anything else that's useful)

**Comment by justaugustus** [comment]
>     * [❌](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/20677499/429800698/1/#/?version=2) - Matt Moore The commit ([e3e0ddb](https://github.com/kubernetes-sigs/bom/commit/e3e0ddb70154062c5c975f92ea0e152e76f2da64)) is not authorized under a signed CLA. [Please click here to be authorized](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/20677499/429800698/1/#/?version=2). For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

@mattmoor -- Can you check out the bot comment and click some buttons in EasyCLA?

**Comment by mattmoor** [comment]
cc @dlorenc

**Comment by mattmoor** [comment]
Should be good!

**Comment by justaugustus** [comment]
> Should be good!

Sweet, thanks Matt!

Adolfo or Veronica, want to do the honors?
/assign @puerco @Verolop 
cc: @kubernetes-sigs/release-engineering 
/hold cancel

**Comment by justaugustus** [comment]
/test all
(Now that https://github.com/kubernetes/test-infra/pull/24428 has merged.)

**Comment by puerco** [comment]
This is an absolutely fantastic PR, thanks a lot!!! :hugs: 
/lgtm

**Comment by justaugustus** [comment]
(I know what the test failures are about. Working on a fix.)

**Comment by justaugustus** [comment]
The verify tests were failing somewhere in the intersection of "works on my laptop" and "works in another repo".

For the first [failure](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_bom/1/pull-bom-verify/1462220143990935552) was from golangci-lint.

k/release is using v1.42.0: https://github.com/kubernetes/release/blob/77ec56f8df8be96367415613ded91e2cf80a2fc3/dependencies.yaml#L306
...while this repo is pulling in an older version (v1.40.1) from sigs.k8s.io/release-utils: https://github.com/kubernetes-sigs/release-utils/blob/66ee61b473d3591023c479c857c3f1d923534d79/dependencies.yaml#L4

A bump to the current version (v1.43.0) fixes any positives in https://github.com/kubernetes-sigs/bom/pull/1/commits/801110824e1033216c9a05d57d4c3147d4594bb0.

The second [failure](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_bom/1/pull-bom-verify/1462493794778746880) incorrectly reports incorrect boilerplate headers in generated files (the truly incorrect headers are fixed in https://github.com/kubernetes-sigs/bom/pull/1/commits/6b1cb4ff50e2d53baef58a1d0d9c0e9e8be34731).

There were some recent updates to k/repo-infra, which may address the boilerplate issues, so I cut a new release ([v0.2.3](https://github.com/kubernetes/repo-infra/releases/tag/v0.2.3)) to pull into https://github.com/kubernetes-sigs/bom/pull/1/commits/801110824e1033216c9a05d57d4c3147d4594bb0.

That didn't work, so I'm thinking there's a discrepancy in how the boilerplate header is being handled.

I'm calling that out-of-scope for this PR and have temporarily disabled the check in https://github.com/kubernetes-sigs/bom/pull/1/commits/a10992ad9a016e6be9ed8835dbe814cb4222580a.

**Comment by puerco** [comment]
> I'm thinking there's a discrepancy in how the boilerplate header is being handled.
I agree. I was trying this morning to reproduce the boilerplate problem by running the magefile locally but simply could not get the same error.

/check-cla

**Comment by justaugustus** [comment]
The old CLA bot is apparently having a bad day.
I attempted to kick it a few different ways, but EasyCLA is passing, so manually applying the `cncf-cla: yes` label again.

@puerco -- Needs a re-/lgtm when you have a chance :)

**Comment by puerco** [comment]
Let's try:
/lgtm

**Comment by justaugustus** [comment]
Woooooooo! 🎉

**Comment by puerco** [comment]
It is in!
/honk

**Comment by puerco** [comment]
Thanks a lot for the mammoth migration PR @justaugustus , you rock :)

**Comment by justaugustus** [comment]
Thanks for all the hard work on the tool, so there was stuff to migrate! ;)

**Pull request merged**
