### PR TITLE
fix: check local image cache first

### LINKED ISSUE #72: bom tries to pull down the image from a registry even if it exists in local image cache
#### What happened:

I built the image, then tried to generate an SBOM for that image but bom tool tried to pull an image from a registry even if it exists locally.

Screen Shot 2022-03-14 at 08 45 42

#### What you expected to happen:

It should generate an SBOM for an image that exists in the local image cache.

#### How to reproduce it (as minimally and precisely as possible):

Try to build an image then run `bom generate -i `

#### Anything else we need to know?:

```shell
$bom version
______  ________  ___
| ___ \|  _  |  \/  |
| |_/ /| | | | .  . |
| ___ \| | | | |\/| |
| |_/ /\ \_/ / |  | |
\____/  \___/\_|  |_/
bom: A tool for working with SPDX manifests

GitVersion:    devel
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
GoVersion:     go1.17.8
Compiler:      gc
Platform:      darwin/amd64
```

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Darwin
- Kernel (e.g. `uname -a`): Darwin C02DM1U3MD6R 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
- Others:

### PR DESCRIPTION
**Pull request by developer-guy**
Fixes #72

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

It will check local image cache before trying to pull image from registry

#### Which issue(s) this PR fixes:

Fixes #72

#### Does this PR introduce a user-facing change?

```release-note
fix: check local image cache first 
```

### CODE REVIEW

**Comment by puerco** [comment]
@developer-guy in addition to the test please change the commit message dropping the "fixes #" (you can leave it in the PR).

**Comment by developer-guy** [comment]
@puerco I think somethings are wrong in Prow pull-bom-verify job, it says:
> Init container clonerefs not ready: (state: waiting, reason: "PodInitializing", message: "") I

**Review by saschagrunert — APPROVED** [review]
/retest

**Review by cpanato — APPROVED** [review]
thanks!
/lgtm

**Pull request merged**
