### PR TITLE
replace references to --directory with --dirs

### PR DESCRIPTION
**Pull request by kfaseela**
Signed-off-by: Faseela K <faseela.k@est.tech>

### CODE REVIEW

**Comment by puerco** [comment]
Thank you @kfaseela, it looks good to me, let me know when the CLA is ready!
/lgtm
/approve
/ok-to-test

**Comment by puerco** [comment]
Retesting, flakes fixed in #25 
/test pull-bom-test

**Comment by kfaseela** [comment]
@puerco will wait for #25 to be merged

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
