### PR TITLE
Fix a small typo in sbom guide

### PR DESCRIPTION
**Pull request by kfaseela**
Signed-off-by: Faseela K <faseela.k@est.tech>

### CODE REVIEW

**Comment by cpanato** [comment]
@kfaseela thanks for your PR, can you please sign the CLA?

**Comment by kfaseela** [comment]
> @kfaseela thanks for your PR, can you please sign the CLA?

Hello, I am trying to get my Corporate CLA working. Hope it will be sorted out soon.

**Review by cpanato — COMMENTED** [review]
thanks
/approve
/lgtm

**Comment by cpanato** [comment]
looks like we have some flaky

/test pull-bom-test

**Pull request merged**
