### PR TITLE
chore: use different base image to include go

### LINKED ISSUE #135: Docker image for `bom` is broken
Trying to obtain SBOM by using `bom` installed via docker image errors with 
```
level=fatal msg="generating doc: creating SPDX document: generating package from directory: scanning go packages: opening new module path: building module package list: unable to get full list of packages, go executable not found "
```

To reproduce use following invocation:
```
podman run -v /home/shivam/work/bom:/opt/stuff/ k8s.gcr.io/bom/bom:v0.3.0  generate /opt/stuff/
```

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Co-authored-by: Jason Hall <jason@chainguard.dev>

#### What type of PR is this?

/kind feature
/kind bug

#### Which issue(s) this PR fixes:

Fixes #135 

#### Special notes for your reviewer:

After a quick chat with @imjasonh, thanks to him, we have agreed that the best way of providing a go binary for an image that is building with ko is changing the image's base with the one of the go binary installed. Fortunately, we have one, https://github.com/distroless/go. [distroless.dev/go](http://distroless.dev/go) is an apko-built distroless image that includes go.

cc: @imjasonh

#### Does this PR introduce a user-facing change?

```release-note
chore: use different base image to include go
```

### CODE REVIEW

**Comment by puerco** [comment]
Thanks for the PR @developer-guy !
This is a great start! I think from here, the next step will be to build our own base image using [apko](https://github.com/chainguard-dev/apko) to include more things beyond just go (such as git for example). But this should fix the broken go dependency problem for now! Thank you.

/ok-to-test

**Comment by puerco** [comment]
Thanks @developer-guy @imjasonh !
/lgtm
/approve

**Comment by developer-guy** [comment]
may I open an issue for this @puerco?

**Comment by justaugustus** [comment]
> may I open an issue for this @puerco?

@developer-guy -- Please do!

**Pull request merged**
