### PR TITLE
Init `sigs.k8s.io/bom` and add presubmits

### PR DESCRIPTION
**Pull request by justaugustus**
- go.mod: Init `sigs.k8s.io/bom`
- Add presubmits

Signed-off-by: Stephen Augustus <foo@auggie.dev>

/assign @puerco @Verolop 
cc: @kubernetes-sigs/release-engineering 
ref: https://github.com/kubernetes/test-infra/pull/24428

### CODE REVIEW

**Comment by cpanato** [comment]
this initial PR will fail because there is nothing to test/lint :)

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
> this initial PR will fail because there is nothing to test/lint :)

/override pull-bom-test
/override pull-bom-verify

**Comment by justaugustus** [comment]
> /lgtm

Manually merging...

**Pull request merged**
