### PR TITLE
Delete canary builds manifests

### PR DESCRIPTION
**Pull request by puerco**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR removes the test image promotion manifests we had set up to build canary images for bom. The manifests now live in k8s-sigs/promo-tools.

Signed-off-by: Adolfo García Veytia (Puerco) <adolfo.garcia@uservers.net>

#### Special notes for your reviewer:

/assign @cpanato 

#### Does this PR introduce a user-facing change?
```release-note
The bom project now features canary releases published to the staging bucket
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by justaugustus — CHANGES_REQUESTED** [review]
Can we update this PR to delete the `canary` directory altogether, now that https://github.com/kubernetes-sigs/promo-tools/pull/529 has landed?

**Comment by puerco** [comment]
We've moved the canary manifests to k-sigs/promo-tools. I've modified the PR to remove the directory as Stephen suggested above.

^^ @justaugustus ptal

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
