### PR TITLE
Cache license network operations

### PR DESCRIPTION
**Pull request by puerco**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This PR introduces two changes into the license downloader:

- After reworking the downloader to get the license zip instead of the individual licenses, we lost the
cache when loading the licenses. This rewired the old cache previously used to cache json files to cache the license list and latest version tag
- The license list downloader implementation now takes a version tag from the downloader options to download the corresponding tag. If blank it will look up the latest tag.

This also drops the old single json file download function which is no longer required (`getLicenseFromURL` )

#### Which issue(s) this PR fixes:

Follow-up to #201 

#### Special notes for your reviewer:

/cc @sbs2001 

#### Does this PR introduce a user-facing change?

```release-note
- The license list downloader now cached the license list zip file
- The license list downloader can now download arbitrary versions of the license list.
```

### CODE REVIEW

**Review by sbs2001 — COMMENTED** [review]
How is the version passed from CLI to the downloader ? Or do you have something else in mind to send version info ?

**Comment by puerco** [comment]
I didn't wire it up to there yet. I wanted to sync with you first on how we would do it considering we will embed one license list.

THIS PR lets us do it, but the change it is mostly meant to address caching.

**Comment by puerco** [comment]
My guess is that we should by default use the embedded version. And then if we get a tag passed via the cli then we can download that.

ALso I was looking at the SBOM and they don't have the license list version, at least not in the JSON version. We need to surface that too.

**Review by cpanato — APPROVED** [review]
/lgtm

if we need to change anything lets do it in a follow up

**Pull request merged**
